/**
 * The demo sellers and their Listings.
 *
 * Every car matches the photographs `photos.manifest.json` lists under its slug: model, generation
 * and year range, colour, body type, and what a badge or a gearbox in the photos shows. Catalog
 * references are by slug (brand, model, region, city) or English name (colour, body type, engine,
 * transmission, drive), as `prisma/seed` writes them; the seed refuses to run if one is missing.
 *
 * No text holds a phone number, a plate or a private person's real name. Private sellers are a
 * first name and an initial; dealership names are invented.
 */
import { demoSellerId } from "./marker";

export type DemoSeller = {
  readonly key: string;
  readonly id: string;
  readonly kind: "private" | "dealership";
  readonly displayName: string;
  readonly locale: "ru" | "tk";
  readonly memberSince: string;
  readonly nameNumber: number;
  readonly avatarIndex: number;
};

export type DemoCar = {
  readonly slug: string;
  readonly sellerKey: string;
  readonly brandSlug: string;
  readonly modelSlug: string;
  readonly year: number;
  readonly mileageKm: number;
  readonly priceAmount: number;
  readonly priceCurrency: "TMT" | "USD" | "AED";
  readonly colorEn: string;
  readonly bodyTypeEn: string;
  readonly engineTypeEn: string;
  readonly transmissionEn: string;
  readonly driveTypeEn: string;
  readonly enginePower: number;
  readonly regionSlug: string;
  readonly citySlug: string;
  readonly condition: "new" | "used";
  readonly damaged: boolean;
  readonly knownIssuesText?: string;
  readonly acceptsExchange: boolean;
  readonly installmentAvailable: boolean;
  readonly descriptionLocale: "ru" | "tk" | "en";
  readonly description: string;
};

const seller = (index: number, fields: Omit<DemoSeller, "id">): DemoSeller => ({
  ...fields,
  id: demoSellerId(index),
});

/** In id order: the index is part of each seller's id, so never reorder or remove an entry. */
export const DEMO_SELLERS: readonly DemoSeller[] = [
  seller(0, {
    key: "ak-yol",
    kind: "dealership",
    displayName: "Ak Ýol Awto Merkezi",
    locale: "tk",
    memberSince: "2024-03-12T08:00:00.000Z",
    nameNumber: 4127,
    avatarIndex: 3,
  }),
  seller(1, {
    key: "mary-motor",
    kind: "dealership",
    displayName: "Мары Мотор Плюс",
    locale: "ru",
    memberSince: "2024-09-02T08:00:00.000Z",
    nameNumber: 7310,
    avatarIndex: 8,
  }),
  seller(2, {
    key: "lebap-awto",
    kind: "dealership",
    displayName: "Lebap Awto Söwda",
    locale: "tk",
    memberSince: "2025-01-20T08:00:00.000Z",
    nameNumber: 2954,
    avatarIndex: 0,
  }),
  seller(3, {
    key: "balkan-trade",
    kind: "dealership",
    displayName: "Балкан Авто Трейд",
    locale: "ru",
    memberSince: "2025-05-14T08:00:00.000Z",
    nameNumber: 6602,
    avatarIndex: 11,
  }),
  seller(4, {
    key: "mekan",
    kind: "private",
    displayName: "Мекан Г.",
    locale: "ru",
    memberSince: "2025-07-03T08:00:00.000Z",
    nameNumber: 1846,
    avatarIndex: 5,
  }),
  seller(5, {
    key: "ayna",
    kind: "private",
    displayName: "Aýna B.",
    locale: "tk",
    memberSince: "2025-11-28T08:00:00.000Z",
    nameNumber: 9033,
    avatarIndex: 2,
  }),
  seller(6, {
    key: "serdar",
    kind: "private",
    displayName: "Сердар М.",
    locale: "ru",
    memberSince: "2026-02-09T08:00:00.000Z",
    nameNumber: 3571,
    avatarIndex: 7,
  }),
  seller(7, {
    key: "dowlet",
    kind: "private",
    displayName: "Döwletmyrat Ç.",
    locale: "tk",
    memberSince: "2026-04-17T08:00:00.000Z",
    nameNumber: 5288,
    avatarIndex: 9,
  }),
  seller(8, {
    key: "rustam",
    kind: "private",
    displayName: "Рустам К.",
    locale: "ru",
    memberSince: "2026-06-30T08:00:00.000Z",
    nameNumber: 8415,
    avatarIndex: 4,
  }),
  seller(9, {
    key: "oraz",
    kind: "private",
    displayName: "Oraz A.",
    locale: "tk",
    memberSince: "2026-08-22T08:00:00.000Z",
    nameNumber: 1209,
    avatarIndex: 10,
  }),
];

const used = { condition: "used", damaged: false, acceptsExchange: false, installmentAvailable: false } as const;
const brandNew = { condition: "new", damaged: false, acceptsExchange: false, installmentAvailable: true } as const;

/**
 * In Listing id order (`marker.ts`), Toyota first as the market is. Append new cars at the end;
 * removing or reordering one changes the ids of the cars after it.
 */
export const DEMO_CARS: readonly DemoCar[] = [
  {
    ...used,
    slug: "camry-xv70-graphite",
    sellerKey: "ak-yol",
    brandSlug: "toyota",
    modelSlug: "camry-hybrid",
    year: 2019,
    mileageKm: 87_000,
    priceAmount: 420_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 218,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    installmentAvailable: true,
    descriptionLocale: "tk",
    description:
      "Toyota Camry Hybrid XLE, Amerikadan getirilen, gümrükden geçirilen. Reňki asyl, kuzowynda boýag ýok. " +
      "Gibrid batareýasy barlanyldy, ýangyç sarp edişi şäherde 5,5 litr töweregi. Salony deri, oturgyçlary ýyladylýar. " +
      "Bölüp tölemek mümkinçiligi bar, jikme-jiklikler üçin çata ýazyň.",
  },
  {
    ...used,
    slug: "camry-xv50-silver",
    sellerKey: "mekan",
    brandSlug: "toyota",
    modelSlug: "camry",
    year: 2013,
    mileageKm: 214_000,
    priceAmount: 255_000,
    priceCurrency: "TMT",
    colorEn: "Silver",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 181,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    acceptsExchange: true,
    descriptionLocale: "ru",
    description:
      "Камри 2.5 XLE, вложений не требует. Масло менял каждые 7 тысяч, есть все чеки. Зимняя резина в подарок. " +
      "Рассмотрю обмен на кроссовер с моей доплатой.",
  },
  {
    ...used,
    slug: "camry-xv50-white",
    sellerKey: "ak-yol",
    brandSlug: "toyota",
    modelSlug: "camry-hybrid",
    year: 2016,
    mileageKm: 158_000,
    priceAmount: 310_000,
    priceCurrency: "TMT",
    colorEn: "White",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 200,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "tk",
    description: "Camry Hybrid LE, ak reňk. Tehniki taýdan doly kadaly, salony arassa. Salonymyza gelip görüp bilersiňiz.",
  },
  {
    ...used,
    slug: "camry-xv50-black",
    sellerKey: "serdar",
    brandSlug: "toyota",
    modelSlug: "camry-hybrid",
    year: 2017,
    mileageKm: 132_000,
    priceAmount: 325_000,
    priceCurrency: "TMT",
    colorEn: "Black",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 200,
    regionSlug: "ahal",
    citySlug: "annau",
    descriptionLocale: "ru",
    description:
      "Продаю свою Камри гибрид XLE. Машина семейная, не такси. Расход по городу около 6 литров. " +
      "На кузове пара мелких сколов на капоте, по ходовой всё сделано весной: стойки, сайлентблоки, тормоза. " +
      "Кожаный салон, камера заднего вида, подогрев сидений. Торг у машины.",
  },
  {
    ...used,
    slug: "camry-xv50-gray",
    sellerKey: "mary-motor",
    brandSlug: "toyota",
    modelSlug: "camry",
    year: 2015,
    mileageKm: 176_000,
    priceAmount: 285_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 181,
    regionSlug: "mary",
    citySlug: "mary",
    installmentAvailable: true,
    descriptionLocale: "ru",
    description: "Camry 2.5 XLE рестайлинг. Пригнана из США, растаможена. Возможна рассрочка через салон.",
  },
  {
    ...used,
    slug: "camry-xv40-gray",
    sellerKey: "dowlet",
    brandSlug: "toyota",
    modelSlug: "camry",
    year: 2010,
    mileageKm: 268_000,
    priceAmount: 185_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 167,
    regionSlug: "dasoguz",
    citySlug: "dasoguz",
    knownIssuesText: "Öňki bamperi täzeden boýaldy. Kondisioner gazy doldurmaly.",
    acceptsExchange: true,
    descriptionLocale: "tk",
    description:
      "Camry 40 XLE, 2.4 motor. Motor, korobka sazlaýyn işleýär, ýag iýmeýär. Öňki bamperi boýaldy, galan ýerleri asyl. " +
      "Kiçiräk maşyna çalyşyk hem bolýar.",
  },
  {
    ...used,
    slug: "highlander-white",
    sellerKey: "ak-yol",
    brandSlug: "toyota",
    modelSlug: "highlander-hybrid",
    year: 2021,
    mileageKm: 46_000,
    priceAmount: 38_500,
    priceCurrency: "USD",
    colorEn: "White",
    bodyTypeEn: "SUV",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "AWD",
    enginePower: 246,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "en",
    description:
      "Highlander Hybrid Platinum, Platinum White Pearl. Panoramic roof, 360 camera, JBL audio, ventilated seats, " +
      "third row. Clean history, one previous owner. Customs cleared and ready to register.",
  },
  {
    ...used,
    slug: "sienna-gray",
    sellerKey: "balkan-trade",
    brandSlug: "toyota",
    modelSlug: "sienna",
    year: 2022,
    mileageKm: 38_000,
    priceAmount: 690_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Minivan",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 245,
    regionSlug: "balkan",
    citySlug: "balkanabat",
    installmentAvailable: true,
    descriptionLocale: "ru",
    description:
      "Toyota Sienna Limited гибрид, 8 мест. Электрические сдвижные двери и багажник, кожаный салон, люк. " +
      "Расход около 7 литров на сотню, для большой семьи лучше варианта нет. Есть рассрочка.",
  },
  {
    ...used,
    slug: "venza-brown",
    sellerKey: "ayna",
    brandSlug: "toyota",
    modelSlug: "venza",
    year: 2014,
    mileageKm: 171_000,
    priceAmount: 290_000,
    priceCurrency: "TMT",
    colorEn: "Brown",
    bodyTypeEn: "Crossover",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "AWD",
    enginePower: 268,
    regionSlug: "ahal",
    citySlug: "tejen",
    acceptsExchange: true,
    descriptionLocale: "tk",
    description: "Venza 3.5 V6, doly ýetirimli. Ýagdaýy örän gowy, garažda saklanýar. Camry bilen çalyşyp bolýar.",
  },
  {
    ...used,
    slug: "prius-silver",
    sellerKey: "rustam",
    brandSlug: "toyota",
    modelSlug: "prius",
    year: 2017,
    mileageKm: 143_000,
    priceAmount: 235_000,
    priceCurrency: "TMT",
    colorEn: "Silver",
    bodyTypeEn: "Hatchback",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 121,
    regionSlug: "lebap",
    citySlug: "turkmenabat",
    descriptionLocale: "ru",
    description:
      "Приус 50-й. Батарея родная, проверял на сервисе, состояние хорошее. Расход 4 литра по городу. " +
      "Продаю, потому что купил машину побольше.",
  },
  {
    ...used,
    slug: "lc300-2023",
    sellerKey: "ak-yol",
    brandSlug: "toyota",
    modelSlug: "land-cruiser",
    year: 2023,
    mileageKm: 21_000,
    priceAmount: 98_000,
    priceCurrency: "USD",
    colorEn: "Black",
    bodyTypeEn: "SUV",
    engineTypeEn: "Diesel",
    transmissionEn: "Automatic",
    driveTypeEn: "4WD",
    enginePower: 304,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "ru",
    description:
      "Land Cruiser 300 ZX, дизель 3.3 V6 твин-турбо. Комплектация ZX: адаптивная подвеска, кожа, обогрев и вентиляция " +
      "сидений, камера кругового обзора, фаркоп. Пробег небольшой, обслуживался у официального дилера, все записи есть. " +
      "Состояние нового автомобиля: без окрасов, без ДТП. Показываем в салоне, возможна проверка на любом сервисе за ваш счёт.",
  },
  {
    ...brandNew,
    slug: "prado-2025",
    sellerKey: "lebap-awto",
    brandSlug: "toyota",
    modelSlug: "land-cruiser-prado",
    year: 2025,
    mileageKm: 15,
    priceAmount: 265_000,
    priceCurrency: "AED",
    colorEn: "White",
    bodyTypeEn: "SUV",
    engineTypeEn: "Diesel",
    transmissionEn: "Automatic",
    driveTypeEn: "4WD",
    enginePower: 204,
    regionSlug: "lebap",
    citySlug: "turkmenabat",
    descriptionLocale: "tk",
    description:
      "Täze Land Cruiser Prado 250, 2.8 dizel, VX. Dubaýdan getirildi, ýöremedik. Kepilnamasy bar. " +
      "Bahasy dirhamda görkezildi, töleg manatda hem kabul edilýär.",
  },
  {
    ...used,
    slug: "rav4-xa30-black",
    sellerKey: "oraz",
    brandSlug: "toyota",
    modelSlug: "rav4",
    year: 2011,
    mileageKm: 196_000,
    priceAmount: 215_000,
    priceCurrency: "TMT",
    colorEn: "Black",
    bodyTypeEn: "Crossover",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "AWD",
    enginePower: 179,
    regionSlug: "mary",
    citySlug: "bayramaly",
    descriptionLocale: "tk",
    description: "RAV4 Limited 2.5, 4WD. Täze tekerler, täze akkumulýator. Gürrüňi bar.",
  },
  {
    ...used,
    slug: "camry-xv70-xse",
    sellerKey: "mary-motor",
    brandSlug: "toyota",
    modelSlug: "camry-hybrid",
    year: 2022,
    mileageKm: 41_000,
    priceAmount: 545_000,
    priceCurrency: "TMT",
    colorEn: "Silver",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 218,
    regionSlug: "mary",
    citySlug: "mary",
    installmentAvailable: true,
    descriptionLocale: "ru",
    description:
      "Camry Hybrid XSE рестайлинг, цвет Precious Metal. Спортивный обвес, 19-дюймовые диски, двухцветная крыша. " +
      "Проекция на лобовое, адаптивный круиз. Возможна рассрочка на 12 месяцев.",
  },
  {
    ...used,
    slug: "highlander-black",
    sellerKey: "mary-motor",
    brandSlug: "toyota",
    modelSlug: "highlander-hybrid",
    year: 2021,
    mileageKm: 63_000,
    priceAmount: 760_000,
    priceCurrency: "TMT",
    colorEn: "Black",
    bodyTypeEn: "SUV",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "AWD",
    enginePower: 246,
    regionSlug: "mary",
    citySlug: "mary",
    acceptsExchange: true,
    descriptionLocale: "ru",
    description: "Highlander Hybrid Platinum, полный привод. Рассмотрим обмен на седан с доплатой.",
  },
  {
    ...brandNew,
    slug: "corolla-cross-2025",
    sellerKey: "lebap-awto",
    brandSlug: "toyota",
    modelSlug: "corolla-cross-hybrid",
    year: 2025,
    mileageKm: 10,
    priceAmount: 98_000,
    priceCurrency: "AED",
    colorEn: "Grey",
    bodyTypeEn: "Crossover",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 122,
    regionSlug: "lebap",
    citySlug: "turkmenabat",
    descriptionLocale: "en",
    description: "Brand new Corolla Cross 1.8 Hybrid, 2025 facelift. Zero kilometres, dealer warranty.",
  },
  {
    ...brandNew,
    slug: "camry-ph-2025",
    sellerKey: "ak-yol",
    brandSlug: "toyota",
    modelSlug: "camry-hybrid",
    year: 2025,
    mileageKm: 25,
    priceAmount: 36_900,
    priceCurrency: "USD",
    colorEn: "White",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 225,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "tk",
    description:
      "Täze nesil Camry 2.5 Hybrid, 2025 ýyl. Ýöremedik, zawod plýonkasy aýrylmadyk. Salonda görüp bilersiňiz. " +
      "Bölüp tölemek şertleri bar.",
  },
  {
    ...used,
    slug: "es-titanium",
    sellerKey: "balkan-trade",
    brandSlug: "lexus",
    modelSlug: "es-300h",
    year: 2020,
    mileageKm: 72_000,
    priceAmount: 640_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 218,
    regionSlug: "balkan",
    citySlug: "turkmenbashi",
    descriptionLocale: "ru",
    description:
      "Lexus ES 300h Executive, цвет Sonic Titanium. Мягкий, тихий, экономичный. Вентиляция сидений, Mark Levinson, " +
      "электрошторка заднего стекла. Один владелец.",
  },
  {
    ...used,
    slug: "rx-blue",
    sellerKey: "ak-yol",
    brandSlug: "lexus",
    modelSlug: "rx-500h",
    year: 2023,
    mileageKm: 9_000,
    priceAmount: 72_000,
    priceCurrency: "USD",
    colorEn: "Blue",
    bodyTypeEn: "Crossover",
    engineTypeEn: "Hybrid",
    transmissionEn: "Automatic",
    driveTypeEn: "AWD",
    enginePower: 371,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "en",
    description:
      "Lexus RX 500h F Sport Performance in Deep Blue Mica. 2.4 turbo hybrid, 371 hp, full-time AWD with rear " +
      "e-axle. Black 21-inch wheels, Mark Levinson sound, head-up display, panoramic roof, heated and ventilated " +
      "seats. Under nine thousand kilometres, kept indoors. A showroom car that was never registered for road use " +
      "abroad; full papers for registration here.",
  },
  {
    ...used,
    slug: "gs-silver",
    sellerKey: "serdar",
    brandSlug: "lexus",
    modelSlug: "gs-350",
    year: 2013,
    mileageKm: 182_000,
    priceAmount: 365_000,
    priceCurrency: "TMT",
    colorEn: "Silver",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "RWD",
    enginePower: 317,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    knownIssuesText: "Стоят чёрные неродные диски, родные отдам. Небольшая вмятина на заднем правом крыле.",
    acceptsExchange: true,
    descriptionLocale: "ru",
    description:
      "Lexus GS 350, задний привод, 3.5 V6. Едет отлично, коробка переключается мягко. Диски неродные. " +
      "Обмен на Land Cruiser Prado с моей доплатой.",
  },
  {
    ...used,
    slug: "nx-gray",
    sellerKey: "lebap-awto",
    brandSlug: "lexus",
    modelSlug: "nx-300h",
    year: 2019,
    mileageKm: 88_000,
    priceAmount: 520_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Crossover",
    engineTypeEn: "Hybrid",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 197,
    regionSlug: "lebap",
    citySlug: "kerki",
    installmentAvailable: true,
    descriptionLocale: "tk",
    description:
      "Lexus NX 300h, Mercury Gray. Gibrid, ýangyjy az iýýär. Salony gara deri, ähli opsiýalary işleýär. " +
      "Kerki şäherinde görmek bolýar, bölüp tölemek mümkin.",
  },
  {
    ...used,
    slug: "accent-white",
    sellerKey: "dowlet",
    brandSlug: "hyundai",
    modelSlug: "accent",
    year: 2009,
    mileageKm: 241_000,
    priceAmount: 98_000,
    priceCurrency: "TMT",
    colorEn: "White",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 112,
    regionSlug: "dasoguz",
    citySlug: "kunya-urgench",
    descriptionLocale: "tk",
    description: "Accent 1.6 awtomat. Ykdysady, ýangyjy az. Ilkinji maşyn üçin gowy.",
  },
  {
    ...used,
    slug: "elantra-cn7-red",
    sellerKey: "balkan-trade",
    brandSlug: "hyundai",
    modelSlug: "elantra",
    year: 2021,
    mileageKm: 67_000,
    priceAmount: 265_000,
    priceCurrency: "TMT",
    colorEn: "Red",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 123,
    regionSlug: "balkan",
    citySlug: "balkanabat",
    descriptionLocale: "ru",
    description:
      "Hyundai Elantra 1.6 Inspiration, цвет Fiery Red. Цифровая панель, большой экран, подогрев руля. " +
      "Машина из Кореи, растаможена. Пробег подтверждён сервисной историей.",
  },
  {
    ...used,
    slug: "elantra-ad-blue",
    sellerKey: "rustam",
    brandSlug: "hyundai",
    modelSlug: "elantra",
    year: 2017,
    mileageKm: 119_000,
    priceAmount: 205_000,
    priceCurrency: "TMT",
    colorEn: "Blue",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Robot/AMT-DCT",
    driveTypeEn: "FWD",
    enginePower: 204,
    regionSlug: "lebap",
    citySlug: "turkmenabat",
    acceptsExchange: true,
    descriptionLocale: "ru",
    description:
      "Elantra Sport 1.6 турбо, робот DCT, 204 л.с. Быстрая и при этом экономичная. Сцепление менял на 100 тысячах. " +
      "Обмен на кроссовер интересен.",
  },
  {
    ...used,
    slug: "sonata-dn8-white",
    sellerKey: "ak-yol",
    brandSlug: "hyundai",
    modelSlug: "sonata",
    year: 2024,
    mileageKm: 14_000,
    priceAmount: 27_500,
    priceCurrency: "USD",
    colorEn: "White",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 160,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    installmentAvailable: true,
    descriptionLocale: "tk",
    description:
      "Täze görnüşli Sonata 2.0, 2024 ýyl, ak reňk. Geçen ýoly az, kepilnamasy dowam edýär. Bölüp tölemek bar.",
  },
  {
    ...used,
    slug: "santafe-tm-black",
    sellerKey: "mekan",
    brandSlug: "hyundai",
    modelSlug: "santa-fe",
    year: 2019,
    mileageKm: 104_000,
    priceAmount: 395_000,
    priceCurrency: "TMT",
    colorEn: "Black",
    bodyTypeEn: "SUV",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 188,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    knownIssuesText: "Скол на лобовом стекле, трещины нет.",
    descriptionLocale: "ru",
    description:
      "Santa Fe 2.4, обслужен полностью: масло, фильтры, свечи, тормозные колодки. Салон чистый, не курили. " +
      "На лобовом небольшой скол. Покупателю без посредников.",
  },
  {
    ...used,
    slug: "palisade-graphite",
    sellerKey: "mary-motor",
    brandSlug: "hyundai",
    modelSlug: "palisade",
    year: 2020,
    mileageKm: 92_000,
    priceAmount: 560_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "SUV",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "AWD",
    enginePower: 295,
    regionSlug: "mary",
    citySlug: "mary",
    descriptionLocale: "ru",
    description:
      "Hyundai Palisade 3.8 V6, полный привод, 8 мест. Цвет Steel Graphite. Подножки, люк, вентиляция сидений " +
      "первого и второго ряда. Большой и комфортный, идеален для дальних поездок.",
  },
  {
    ...used,
    slug: "cerato-black",
    sellerKey: "ayna",
    brandSlug: "kia",
    modelSlug: "cerato",
    year: 2008,
    mileageKm: 233_000,
    priceAmount: 88_000,
    priceCurrency: "TMT",
    colorEn: "Black",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 122,
    regionSlug: "ahal",
    citySlug: "tejen",
    acceptsExchange: true,
    descriptionLocale: "tk",
    description: "Kia Cerato 1.6. Arzan we ygtybarly. Çalyşyk bolýar.",
  },
  {
    ...used,
    slug: "sportage-nq5",
    sellerKey: "lebap-awto",
    brandSlug: "kia",
    modelSlug: "sportage-hybrid",
    year: 2023,
    mileageKm: 31_000,
    priceAmount: 480_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Crossover",
    engineTypeEn: "Hybrid",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 230,
    regionSlug: "lebap",
    citySlug: "turkmenabat",
    installmentAvailable: true,
    descriptionLocale: "tk",
    description:
      "Kia Sportage Hybrid, mat çal reňk (Shadow Matte Gray). 1.6 turbo gibrid, 230 at güýji. Iki ekranly panel, " +
      "elektrik bagažnik, oturgyçlary ýyladylýar we sowadylýar. Koreýadan getirilen, gümrügi tölenen. " +
      "Mat reňk üçin ýörite ýuwuş serişdesini sowgat berýäris.",
  },
  {
    ...used,
    slug: "sorento-xm",
    sellerKey: "balkan-trade",
    brandSlug: "kia",
    modelSlug: "sorento",
    year: 2013,
    mileageKm: 207_000,
    priceAmount: 235_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "SUV",
    engineTypeEn: "Diesel",
    transmissionEn: "Automatic",
    driveTypeEn: "AWD",
    enginePower: 197,
    regionSlug: "balkan",
    citySlug: "turkmenbashi",
    descriptionLocale: "ru",
    description: "Kia Sorento 2.2 дизель, полный привод. Экономичный и тяговитый, для трассы то что нужно.",
  },
  {
    ...used,
    slug: "rio-gray",
    sellerKey: "dowlet",
    brandSlug: "kia",
    modelSlug: "rio",
    year: 2004,
    mileageKm: 289_000,
    priceAmount: 54_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Hatchback",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 98,
    regionSlug: "dasoguz",
    citySlug: "dasoguz",
    damaged: true,
    knownIssuesText: "Korobka geçende urgy berýär, abatlamaly. Arka bamperinde çyzyklar bar.",
    descriptionLocale: "tk",
    description:
      "Kia Rio hatchback, köne bolsa-da ýöreýär. Awtomat korobkasyny abatlamaly, şonuň üçin bahasy arzan. " +
      "Ussa üçin amatly wariant.",
  },
  {
    ...used,
    slug: "stinger-red",
    sellerKey: "serdar",
    brandSlug: "kia",
    modelSlug: "stinger",
    year: 2019,
    mileageKm: 78_000,
    priceAmount: 470_000,
    priceCurrency: "TMT",
    colorEn: "Red",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "AWD",
    enginePower: 370,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "en",
    description:
      "Kia Stinger GT 3.3 twin turbo, AWD, HiChroma Red. Brembo brakes, Harman Kardon, heated and ventilated seats. " +
      "Serviced on time, never tracked.",
  },
  {
    ...used,
    slug: "carnival-white",
    sellerKey: "lebap-awto",
    brandSlug: "kia",
    modelSlug: "carnival",
    year: 2024,
    mileageKm: 12_000,
    priceAmount: 145_000,
    priceCurrency: "AED",
    colorEn: "White",
    bodyTypeEn: "Minivan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 294,
    regionSlug: "lebap",
    citySlug: "turkmenabat",
    descriptionLocale: "ru",
    description:
      "Kia Carnival 3.5 рестайлинг, 2024 год, 8 мест. Пригнан из ОАЭ, растаможен. Электрические сдвижные двери, " +
      "два экрана, камера 360. Цена указана в дирхамах, оплата в манатах по курсу.",
  },
  {
    ...used,
    slug: "bmw-f10-black",
    sellerKey: "mekan",
    brandSlug: "bmw",
    modelSlug: "5-series",
    year: 2012,
    mileageKm: 188_000,
    priceAmount: 210_000,
    priceCurrency: "TMT",
    colorEn: "Black",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Diesel",
    transmissionEn: "Automatic",
    driveTypeEn: "RWD",
    enginePower: 184,
    regionSlug: "ahal",
    citySlug: "gekdepe",
    descriptionLocale: "ru",
    description: "BMW 520d F10, дизель, расход 6 литров. Ухоженная, обслуживалась на BMW-сервисе.",
  },
  {
    ...used,
    slug: "bmw-e39-silver",
    sellerKey: "rustam",
    brandSlug: "bmw",
    modelSlug: "5-series",
    year: 2002,
    mileageKm: 312_000,
    priceAmount: 79_000,
    priceCurrency: "TMT",
    colorEn: "Silver",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "RWD",
    enginePower: 192,
    regionSlug: "lebap",
    citySlug: "turkmenabat",
    damaged: true,
    knownIssuesText: "Течь масла из-под клапанной крышки, нужен ремонт системы охлаждения: помпа и радиатор.",
    acceptsExchange: true,
    descriptionLocale: "ru",
    description:
      "Классика, BMW 525i E39 рестайлинг. Кузов живой, без ржавчины. Требуется ремонт охлаждения, поэтому цена ниже рынка. " +
      "Обмен на что-нибудь японское.",
  },
  {
    ...used,
    slug: "bmw-g30-white",
    sellerKey: "ak-yol",
    brandSlug: "bmw",
    modelSlug: "5-series",
    year: 2021,
    mileageKm: 36_000,
    priceAmount: 55_000,
    priceCurrency: "USD",
    colorEn: "White",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "AWD",
    enginePower: 530,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "tk",
    description:
      "BMW M550i xDrive, 4.4 V8, 530 at güýji. Mineral White. Doly ýetirimli, Harman Kardon, lazer çyralar. " +
      "Ýagdaýy täze ýaly, hiç hili urgy ýok.",
  },
  {
    ...used,
    slug: "mb-w204-white",
    sellerKey: "balkan-trade",
    brandSlug: "mercedes-benz",
    modelSlug: "c-class",
    year: 2009,
    mileageKm: 221_000,
    priceAmount: 145_000,
    priceCurrency: "TMT",
    colorEn: "White",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "RWD",
    enginePower: 204,
    regionSlug: "balkan",
    citySlug: "balkanabat",
    descriptionLocale: "ru",
    description: "Mercedes C230 W204, пакет AMG. Хорошее состояние для своих лет.",
  },
  {
    ...used,
    slug: "mb-w213-grey",
    sellerKey: "mary-motor",
    brandSlug: "mercedes-benz",
    modelSlug: "e-class",
    year: 2021,
    mileageKm: 54_000,
    priceAmount: 640_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "RWD",
    enginePower: 211,
    regionSlug: "mary",
    citySlug: "bayramaly",
    installmentAvailable: true,
    descriptionLocale: "ru",
    description:
      "Mercedes-Benz E 250 Exclusive, рестайлинг 2021 года. Цвет Granite Grey. Мультируль, виртуальная панель, " +
      "ambient-подсветка, Burmester. Обслуживание только у дилера. Возможна рассрочка.",
  },
  {
    ...used,
    slug: "mb-g-black",
    sellerKey: "ak-yol",
    brandSlug: "mercedes-benz",
    modelSlug: "g-class",
    year: 2020,
    mileageKm: 48_000,
    priceAmount: 128_000,
    priceCurrency: "USD",
    colorEn: "Black",
    bodyTypeEn: "SUV",
    engineTypeEn: "Diesel",
    transmissionEn: "Automatic",
    driveTypeEn: "4WD",
    enginePower: 330,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "en",
    description: "Mercedes-Benz G 400 d, Obsidian Black. Three locking differentials, original paint, full service book.",
  },
  {
    ...used,
    slug: "altima-gun",
    sellerKey: "serdar",
    brandSlug: "nissan",
    modelSlug: "altima",
    year: 2020,
    mileageKm: 96_000,
    priceAmount: 235_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "CVT",
    driveTypeEn: "FWD",
    enginePower: 182,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    descriptionLocale: "ru",
    description: "Nissan Altima 2.5 SL, кожа, подогрев. Вариатор обслужен, масло менял на 90 тысячах.",
  },
  {
    ...used,
    slug: "xtrail-black",
    sellerKey: "ayna",
    brandSlug: "nissan",
    modelSlug: "x-trail",
    year: 2011,
    mileageKm: 224_000,
    priceAmount: 158_000,
    priceCurrency: "TMT",
    colorEn: "Black",
    bodyTypeEn: "Crossover",
    engineTypeEn: "Gasoline",
    transmissionEn: "CVT",
    driveTypeEn: "AWD",
    enginePower: 169,
    regionSlug: "ahal",
    citySlug: "annau",
    damaged: true,
    knownIssuesText: "Wariatoryň (CVT) sesi bar, barlamaly ýa-da çalyşmaly.",
    descriptionLocale: "tk",
    description:
      "Nissan X-Trail 2.5, doly ýetirimli. Kuzowy gowy, salony arassa. Wariatory abatlamaly, şonuň üçin bahasy arzan goýuldy.",
  },
  {
    ...used,
    slug: "malibu-red",
    sellerKey: "dowlet",
    brandSlug: "chevrolet",
    modelSlug: "malibu",
    year: 2013,
    mileageKm: 176_000,
    priceAmount: 135_000,
    priceCurrency: "TMT",
    colorEn: "Burgundy",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 170,
    regionSlug: "dasoguz",
    citySlug: "dasoguz",
    knownIssuesText: "Kondisioner gowşak sowadýar.",
    acceptsExchange: true,
    descriptionLocale: "tk",
    description: "Chevrolet Malibu LTZ 2.4, goýy gyzyl reňk. Kondisioner gowşak, galany kadaly. Çalyşyk bolýar.",
  },
  {
    ...used,
    slug: "accord-metal",
    sellerKey: "balkan-trade",
    brandSlug: "honda",
    modelSlug: "accord",
    year: 2011,
    mileageKm: 198_000,
    priceAmount: 170_000,
    priceCurrency: "TMT",
    colorEn: "Grey",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 275,
    regionSlug: "balkan",
    citySlug: "turkmenbashi",
    knownIssuesText: "Царапины на заднем бампере и крышке багажника.",
    descriptionLocale: "ru",
    description: "Honda Accord 3.5 V6. Мотор мощный и надёжный, коробка без нареканий. На заднем бампере царапины.",
  },
  {
    ...used,
    slug: "passat-silver",
    sellerKey: "mekan",
    brandSlug: "volkswagen",
    modelSlug: "passat",
    year: 2008,
    mileageKm: 276_000,
    priceAmount: 99_000,
    priceCurrency: "TMT",
    colorEn: "Silver",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Diesel",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 140,
    regionSlug: "ashgabat",
    citySlug: "ashgabat-city",
    damaged: true,
    knownIssuesText: "Турбина свистит и не всегда выходит на давление, нужна замена или ремонт.",
    descriptionLocale: "ru",
    description: "Passat B6 2.0 TDI. Нужен ремонт турбины, в остальном машина живая. Цена с учётом ремонта.",
  },
  {
    ...used,
    slug: "a6-silver",
    sellerKey: "mary-motor",
    brandSlug: "audi",
    modelSlug: "a6",
    year: 2013,
    mileageKm: 201_000,
    priceAmount: 215_000,
    priceCurrency: "TMT",
    colorEn: "Silver",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Diesel",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 177,
    regionSlug: "mary",
    citySlug: "mary",
    descriptionLocale: "en",
    description: "Audi A6 C7 2.0 TDI, Ice Silver. Economical on long trips, comfortable cabin.",
  },
  {
    ...used,
    slug: "lancer-acg",
    sellerKey: "oraz",
    brandSlug: "mitsubishi",
    modelSlug: "lancer",
    year: 2008,
    mileageKm: 280_000,
    priceAmount: 92_000,
    priceCurrency: "TMT",
    colorEn: "Beige",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Manual",
    driveTypeEn: "FWD",
    enginePower: 109,
    regionSlug: "mary",
    citySlug: "bayramaly",
    acceptsExchange: true,
    descriptionLocale: "tk",
    description:
      "Mitsubishi Lancer 1.5, mehaniki korobka. Ýangyjy az, bejergisi arzan. Salony matadan, arassa. " +
      "Çalyşyk hem bolýar.",
  },
  {
    ...used,
    slug: "cruze-white",
    sellerKey: "lebap-awto",
    brandSlug: "chevrolet",
    modelSlug: "cruze",
    year: 2017,
    mileageKm: 121_000,
    priceAmount: 160_000,
    priceCurrency: "TMT",
    colorEn: "White",
    bodyTypeEn: "Sedan",
    engineTypeEn: "Gasoline",
    transmissionEn: "Automatic",
    driveTypeEn: "FWD",
    enginePower: 153,
    regionSlug: "lebap",
    citySlug: "kerki",
    descriptionLocale: "tk",
    description: "Chevrolet Cruze LTZ 1.4 turbo, ak reňk. Ykdysady we rahat. Kerki şäherinde.",
  },
];
