export const REALTIME_ERROR_CODES = {
  MISSING_AUTH_TOKEN: "MISSING_AUTH_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_TOKEN_PAYLOAD: "INVALID_TOKEN_PAYLOAD",
} as const;

export type RealtimeErrorCode =
  (typeof REALTIME_ERROR_CODES)[keyof typeof REALTIME_ERROR_CODES];
