// Literal expected wording from the approved identity prototype at 7382e77.
export const profilePhotoCopy = {
  "en": {
    "photoT": "Profile photo",
    "changePhoto": "Change profile photo",
    "takePhoto": "Take photo",
    "chooseLib": "Choose from library",
    "removePhoto": "Remove photo",
    "permT": "Camera access is off",
    "permD": "To take a photo, allow camera access for AutoTM in system settings.",
    "openSettings": "Open settings",
    "uploading": "Uploading photo... 25%",
    "photoFail": "Couldn't upload the photo.",
    "photoBig": "This photo is too large. Choose one up to 5 MB.",
    "photoType": "This file can't be used. Choose a JPEG, PNG or WebP photo.",
    "chooseOther": "Choose another photo",
    "photoSaved": "Photo updated",
    "photoRemoved": "Photo removed",
    "photoRmFail": "Couldn't remove the photo.",
    "offline": "No internet connection. Try again when you are online.",
    "preparing": "Preparing photo...",
    "attached": "This upload belongs to a listing. Retry to upload a new copy.",
    "retry": "Retry",
    "cancel": "Cancel"
  },
  "ru": {
    "photoT": "Фото профиля",
    "changePhoto": "Изменить фото профиля",
    "takePhoto": "Сделать фото",
    "chooseLib": "Выбрать из галереи",
    "removePhoto": "Удалить фото",
    "permT": "Нет доступа к камере",
    "permD": "Чтобы сделать фото, разрешите AutoTM доступ к камере в настройках системы.",
    "openSettings": "Открыть настройки",
    "uploading": "Загрузка фото... 25%",
    "photoFail": "Не удалось загрузить фото.",
    "photoBig": "Фото слишком большое. Выберите фото до 5 МБ.",
    "photoType": "Этот файл не подходит. Выберите фото в формате JPEG, PNG или WebP.",
    "chooseOther": "Выбрать другое фото",
    "photoSaved": "Фото обновлено",
    "photoRemoved": "Фото удалено",
    "photoRmFail": "Не удалось удалить фото.",
    "offline": "Нет подключения к интернету. Попробуйте позже.",
    "preparing": "Подготовка фото...",
    "attached": "Это фото уже используется в объявлении. Повторите загрузку новой копии.",
    "retry": "Повторить",
    "cancel": "Отмена"
  },
  "tk": {
    "photoT": "Profil suraty",
    "changePhoto": "Profil suratyny üýtget",
    "takePhoto": "Surata al",
    "chooseLib": "Galereýadan saýla",
    "removePhoto": "Suraty aýyr",
    "permT": "Kamera rugsady ýok",
    "permD": "Surata almak üçin ulgam sazlamalarynda AutoTM-e kamera rugsadyny beriň.",
    "openSettings": "Sazlamalary aç",
    "uploading": "Surat ýüklenýär... 25%",
    "photoFail": "Suraty ýükläp bolmady.",
    "photoBig": "Surat gaty uly. 5 MB-dan uly bolmadyk surat saýlaň.",
    "photoType": "Bu faýl ýaramaýar. JPEG, PNG ýa-da WebP surat saýlaň.",
    "chooseOther": "Başga surat saýla",
    "photoSaved": "Surat täzelendi",
    "photoRemoved": "Surat aýryldy",
    "photoRmFail": "Suraty aýryp bolmady.",
    "offline": "Internet baglanyşygy ýok. Soňrak synanyşyň.",
    "preparing": "Surat taýýarlanýar...",
    "attached": "Bu surat bildirişde ulanylýar. Täze nusgasyny ýükläp, täzeden synanyşyň.",
    "retry": "Täzeden synanyş",
    "cancel": "Ýatyr"
  }
} as const;
